server:
  port: 9090

spring:
  config:
    activate:
      on-profile: local
    import: application-secret.yml
  application:
    name: member-service
  datasource:
    url: jdbc:mariadb://localhost:3310/dongsanginong?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    defer-datasource-initialization: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+9
  sql:
    init:
      mode: always

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: member-group
      auto-offset-reset: earliest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: info

### swagger
#springdoc:
#  api-docs:
#    path: /member-service/v3/api-docs
#  swagger-ui:
#    path: /member-service/swagger-ui.html
#
#openapi:
#  service:
#    # API Gateway port
#    url: http://localhost:8080